# Generated by Django 5.2.4 on 2025-07-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_productimage_image_url_productdetail_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='application_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='packaging',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='skin_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
