# Generated by Django 5.2.4 on 2025-07-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productdetail_application_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='Description',
        ),
    ]
