# Generated by Django 5.2.4 on 2025-07-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_productdetail_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='rating',
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='is_color',
            field=models.BooleanField(default=False),
        ),
    ]
