# Generated by Django 5.2.4 on 2026-05-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_accesstoken_user_alter_accesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(default='5da162268fab427abd73cc9a0ee06e25', max_length=64, unique=True),
        ),
    ]
