# Generated by Django 5.2.4 on 2026-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_accesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(default='b479ddbc1172430c8a193dc77692e958', max_length=64, unique=True),
        ),
    ]
