# Generated by Django 5.2.4 on 2026-06-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_customer_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(default='4eb8e3e75ecf4dbb9c3a1a93ae70d4ad', max_length=64, unique=True),
        ),
    ]
